# Generated by Django 4.1.7 on 2023-04-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='popularvideo',
            name='dsc',
            field=models.TextField(default='rtest'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='popularvideo',
            name='titulo',
            field=models.CharField(default='tyes', max_length=50),
            preserve_default=False,
        ),
    ]
